#!/data/data/com.termux/files/usr/bin/bash

# Variants
IMAGE_PATH="/data/data/com.termux/files/home/archlinux.img"
MOUNT_PATH="/data/local/tmp/archlinux"

# Grant root
if [ "$(id -u)" -ne 0 ]; then
    ./elevator $0 $@
    exit
fi

# Create mount dir
mkdir -p "$MOUNT_PATH"

# Mount
mount -t ext4 -o loop,rw,suid,dev,exec "$IMAGE_PATH" "$MOUNT_PATH"
mount -t proc proc "$MOUNT_PATH/proc"
mount -t sysfs sysfs "$MOUNT_PATH/sys"
mount -t tmpfs tmpfs "$MOUNT_PATH/tmp"
mount --bind /dev "$MOUNT_PATH/dev"
mount --bind /dev/pts "$MOUNT_PATH/dev/pts"
if [ ! -d "$MOUNT_PATH/dev/shm" ]; then
    mkdir -p "$MOUNT_PATH/dev/shm"
fi
mount -t tmpfs -o size=256M tmpfs "$MOUNT_PATH/dev/shm"

# Fix DNS
RESOLV_CONF="$MOUNT_PATH/etc/resolv.conf"
if [ -L "$RESOLV_CONF" ]; then
    rm "$RESOLV_CONF"
fi
echo "nameserver 114.114.114.114" > "$RESOLV_CONF"
echo "nameserver 8.8.8.8" >> "$RESOLV_CONF"

# Enter chroot
unset LD_PRELOAD
chroot "$MOUNT_PATH" /usr/bin/env -i \
	TERM="$TERM" \
	su - shigure

# Exit
umount -l "$MOUNT_PATH/dev/shm"
umount -l "$MOUNT_PATH/dev/pts"
umount -l "$MOUNT_PATH/dev"
umount -l "$MOUNT_PATH/proc"
umount -l "$MOUNT_PATH/sys"
umount -l "$MOUNT_PATH/tmp"
umount -l "$MOUNT_PATH"
